-- Run this AFTER supabase-schema.sql in Supabase SQL Editor.
-- It adds one shared household per owner and secure email-based family access.
create table if not exists public.households (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now());
create table if not exists public.household_members (household_id uuid not null references public.households(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role text not null default 'Viewer' check(role in ('Owner','Viewer')), primary key(household_id,user_id));
create table if not exists public.household_invites (household_id uuid not null references public.households(id) on delete cascade, email text not null, invited_by uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), unique(household_id,email));
alter table public.household_invites add column if not exists name text;
alter table public.appliances add column if not exists household_id uuid references public.households(id) on delete cascade;

-- Migrates existing owner data into a household using the owner's profile ID.
insert into public.households(id) select id from public.profiles on conflict do nothing;
insert into public.household_members(household_id,user_id,role) select id,id,'Owner' from public.profiles on conflict do nothing;
update public.appliances set household_id=user_id where household_id is null;

create or replace function public.is_household_member(target_household uuid) returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from public.household_members where household_id=target_household and user_id=auth.uid()) $$;
alter table public.households enable row level security; alter table public.household_members enable row level security; alter table public.household_invites enable row level security;
drop policy if exists "own appliances" on public.appliances; drop policy if exists "own services" on public.services; drop policy if exists "own profile" on public.profiles; drop policy if exists "read own profile" on public.profiles; drop policy if exists "update own profile" on public.profiles; drop policy if exists "read own membership" on public.household_members; drop policy if exists "household appliance access" on public.appliances; drop policy if exists "household service access" on public.services;
create policy "read own profile" on public.profiles for select to authenticated using(id=auth.uid());
create policy "update own profile" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "read own membership" on public.household_members for select to authenticated using(user_id=auth.uid());
create policy "household appliance access" on public.appliances for all to authenticated using(public.is_household_member(household_id)) with check(public.is_household_member(household_id));
create policy "household service access" on public.services for all to authenticated using(exists(select 1 from public.appliances a where a.id=appliance_id and public.is_household_member(a.household_id))) with check(exists(select 1 from public.appliances a where a.id=appliance_id and public.is_household_member(a.household_id)));
grant usage on schema public to authenticated; grant select,insert,update,delete on public.profiles,public.appliances,public.services,public.household_members to authenticated;

create or replace function public.get_household_members() returns table(id uuid,full_name text,email text,profile_pic text,role text) language sql security definer set search_path=public as $$ select p.id,p.full_name,p.email,p.profile_pic,m.role from public.household_members m join public.profiles p on p.id=m.user_id where m.household_id=(select household_id from public.household_members where user_id=auth.uid() limit 1) order by m.role='Owner' desc,p.full_name $$;
create or replace function public.get_household_invites() returns table(name text,email text) language sql security definer set search_path=public as $$ select i.name,i.email from public.household_invites i where i.household_id=(select household_id from public.household_members where user_id=auth.uid() limit 1) and not exists(select 1 from public.profiles p where lower(p.email)=lower(i.email)) order by i.created_at desc $$;
drop function if exists public.invite_household_member(text);
create or replace function public.invite_household_member(invitee_name text,invitee_email text) returns void language plpgsql security definer set search_path=public as $$ declare hid uuid; invited_id uuid; old_hid uuid; begin select household_id into hid from public.household_members where user_id=auth.uid() and role='Owner' limit 1; if hid is null then raise exception 'Only the household owner can add family members'; end if; insert into public.household_invites(household_id,name,email,invited_by) values(hid,invitee_name,lower(invitee_email),auth.uid()) on conflict(household_id,email) do update set name=excluded.name; select id into invited_id from public.profiles where lower(email)=lower(invitee_email); if invited_id is not null then select household_id into old_hid from public.household_members where user_id=invited_id and role='Owner' limit 1; if old_hid is not null and old_hid<>hid and exists(select 1 from public.appliances where household_id=old_hid) then raise exception 'This account already owns appliance records and cannot be moved automatically'; end if; if old_hid is not null and old_hid<>hid then delete from public.household_members where household_id=old_hid and user_id=invited_id; end if; insert into public.household_members(household_id,user_id,role) values(hid,invited_id,'Viewer') on conflict do nothing; end if; end; $$;
grant execute on function public.get_household_members(),public.get_household_invites(),public.invite_household_member(text,text) to authenticated;

-- New accounts join an existing email invitation, otherwise receive their own household.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare hid uuid; begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')); select household_id into hid from public.household_invites where lower(email)=lower(new.email) order by created_at limit 1; if hid is null then hid:=new.id; insert into public.households(id) values(hid) on conflict do nothing; insert into public.household_members(household_id,user_id,role) values(hid,new.id,'Owner') on conflict do nothing; else insert into public.household_members(household_id,user_id,role) values(hid,new.id,'Viewer') on conflict do nothing; end if; return new; end; $$;
