-- Run this once in Supabase SQL Editor. It creates private per-user data.
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null, full_name text not null default '', profile_pic text, created_at timestamptz not null default now());
create table if not exists public.appliances (id text primary key, user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade, name text not null, brand text not null, model text not null, serial_number text, purchase_date date not null, purchase_price numeric not null check(purchase_price>=0), warranty_months integer not null check(warranty_months>=0), lifespan_years integer not null check(lifespan_years>0), room text not null, status text not null check(status in ('Operational','Needs Service','Replace Suggested')), image_url text, notes text, created_at timestamptz not null default now());
create table if not exists public.services (id text primary key, appliance_id text not null references public.appliances(id) on delete cascade, date date not null, type text not null, cost numeric not null check(cost>=0), technician text, phone text, description text not null, created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.appliances enable row level security; alter table public.services enable row level security;
create policy "own profile" on public.profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy "own appliances" on public.appliances for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "own services" on public.services for all using (exists(select 1 from public.appliances a where a.id=appliance_id and a.user_id=auth.uid())) with check (exists(select 1 from public.appliances a where a.id=appliance_id and a.user_id=auth.uid()));
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end; $$;
create or replace trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
